### ISSUE TITLE
tm!menu

### ISSUE THREAD

**Issue by meyskens** [itfactory-tm/thomas-bot#66]
*Note: you might need to be a little bit of a masochist to code this*

This idea came to me while shouting at Sharepoint

```
> tm!menu
Bot:
Soep: Tomatengroentensoep 
Broodje van de dag: Club kaas , hesp of club martino
Lunch: Lasagna
Veggie: Quorn
Snack: curryworst
```

The idea: Sharepoint API using https://go.spflow.com/auth/overview
Auth: my account? To be tested
Reading data? Scraping the HTML, parsing it and giving the options in a BETTER way than represented

Stretch goals: `tm!menu Woensdag`

**Comment by Victonator** [comment]
There's no menu to be found on sharepoint at the moment, but if there is, I'd like to accept the task ^^

**Comment by Nanotect** [comment]
I'm on it! There is no menu yet, but all of the groundwork can already be prepared

It seems like the SPO from the ADFS strategy from Gosip might be the way forward.
As the example authentication JSON shows:
```
{
  "siteUrl": "https://contoso.sharepoint.com/sites/test",
  "username": "john.doe@contoso.onmicrosoft.com",
  "password": "this-is-not-a-real-password"
 }
```
means that this method does not require extra access tokens, I'll try to work something out and investigate further
