### ISSUE TITLE
Add translate command

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [itfactory-tm/thomas-bot#8]
Often we want to translate something to another language, so a command would be very convenient.

Google offers a paid API with a limited free tier, although a reverse engineered implementation of the private API can be found [here (js)](https://github.com/matheuss/google-translate-token) and [here (C#)](https://gist.github.com/HoLLy-HaCKeR/2e9521532d6196330e52b2a276572db6). The latter also supports text-to-speech :)

**Comment by meyskens** [comment]
Going to close this as out of scope for this project
